#!/bin/bash
# vim: ts=4 sw=4:

# remote testing session
SDIR="/x_proj/jenov/scripts"
BIN="ymake_dev3"
CMD="ymake_dev3"
GRUB="grub.cfg"
LIB="y_bash_lib"
DEST_LIB="/usr/local/bin"
DEST_BIN="/usr/local/bin"
DEST_GRUB="/boot/grub"
DISK="nvme0n1"
PART="p5"
PRE_CMD="mount /xdev"
POST_CMD="umount /xdev"
#PAR=$*
MODE=$1

while [ -n "$1" ] ; do
    case $1 in
        --DISK|-d) DISK="$2"; shift;;
        --update) UPDATE="true";;
        *) PAR="$PAR $1";;
    esac
    shift
done

test -b /dev/${DISK} || {
    echo Invalid block device [/dev/${DISK}]
    exit 1
}

DEF_NEW="       --new_dev --mountmisc  -sync  -clgentoo  -update  -prechg  -check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild --qtest  --tools  -systest -D"
DEF_MOUNT="      -new_dev --mountmisc  -sync  -clgentoo  -update --prechg  -check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild --qtest   -tools  -systest -D"
DEF_SYNC="       -new_dev  -mountmisc --sync  -clgentoo  -update           -check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild  -qtest   -tools  -systest -D"
DEF_CHECK="      -new_dev --mountmisc  -sync  -clgentoo --update          --check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild  -qtest   -tools  -systest -D"
DEF_NEW_KERNEL=" -new_dev --mountmisc  -sync  -clgentoo  -update           -check  -build  -resume  -ckernel  --bkernel  -lilo  -grub_inst  -grub --rebuild --qtest   -tools  -systest -D"
DEF_TEST="       -new_dev --mountmisc  -sync  -clgentoo  -update           -check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild --qtest   -tools  -systest -D"
DEF_BUILD="      -new_dev --mountmisc  -sync  -clgentoo --update --prechg --check --build  -resume  -ckernel   -bkernel  -lilo --grub_inst  -grub  -rebuild  -qtest   -tools  -systest -D"
DEF_TOOLS="      -new_dev --mountmisc  -sync  -clgentoo  -update  -prechg  -check  -build  -resume  -ckernel   -bkernel  -lilo  -grub_inst  -grub  -rebuild  -qtest  --tools  -systest -D"
DEF_ALL="        -new_dev --mountmisc  -sync  -clgentoo  -update  -prechg  -check --build  -resume --ckernel  --bkernel  -lilo  -grub_inst  -grub --rebuild --qtest  --tools  -systest -D"
DEF_RESUME="     -new_dev --mountmisc  -sync  -clgentoo  -update  -prechg  -check  -build --resume  -ckernel  --bkernel  -lilo  -grub_inst  -grub --rebuild --qtest  --tools  -systest -D"

test -n "$MODE" && eval CURRENT='$'"DEF_"$MODE
test -z "$CURRENT" -o "$CURRENT" = "$MODE" && { 
    echo MISSING mode definition
    env | grep DEF_
    exit 1; 
}

test -n "$UPDATE" && {
    test -e $SDIR/$BIN && cp $SDIR/$BIN $DEST_BIN 1>/dev/null
    test -e $SDIR/$LIB && cp $SDIR/$LIB $DEST_LIB 1>/dev/null
    test -e $SDIR/$GRUB && cp $SDIR/$GRUB $DEST_GRUB 1>/dev/null
}

#$PRE_CMD
$CMD --src_fstab /etc/fstab.dev --disk $DISK --part $PART  --mnt /mnt $CURRENT $PAR
#$POST_CMD
