#!/bin/bash

CMD="ping -c 1 -n google.com"
TMAX=0
rm dump.txt
while true ; do
    ETIME=`$CMD | grep "time="`
    x=${ETIME##*time=}
    #echo $x >> dump.txt
    x1=${x%%'.'*}
    test -z "$x1" && x1=$x
    x2=${x1%%' '*}
    #echo [$x2] >> dump.txt
    if [ $TMAX -lt $x2 ] ; then
        TMAX=${x2}
    fi
    #echo [$TMAX]
    echo -n -e '\r'Max ping time: $TMAX ms
done
echo
