#!/bin/bash

CMD="ping -c 1 -n google.com"
TMAX=0
TAV=0
DEBUG=/tmp/pingtest.debug
rm -f $DEBUG
touch $DEBUG
echo Start: `date` >> $DEBUG
while true ; do
    ETIME=`$CMD | grep "time="`
    if [[ -z "$ETIME" ]]; then
        continue
    fi
    x=${ETIME##*time=}
    x1=${x%%'.'*}
    test -z "$x1" && x1=$x
    x2=${x1%%' '*}
    if [[ -z "$x2" ]]; then 
        echo [$ETIME] >> $DEBUG
        continue
    fi
    if [ $TMAX -lt $x2 ] ; then
        TMAX=${x2}
    fi
    printf "Ping times:  %04.d / %-04.d\r" $x2 $TMAX
    sleep 1
done
echo
