#!/bin/bash

PORT="/dev/ttyUSB0"
CLOSE="C"
OPEN="O"
RESET="L3"

cmd () {
    echo AT+${1}${2}
    echo AT+${1}${2} > $PORT
    sleep 1
    #od -x < $PORT
}

test_1 () {
    W=2
    cmd $RESET
    cmd $OPEN 1
    sleep $W
    cmd $OPEN 2
    sleep $W
    cmd $RESET
}
test_1

