#!/bin/bash
echo `date +%Y%m%d-%H:%M` "ylock activated" >> /var/log/ydebug.log
i3lock -c 000000 && echo disk > /sys/power/state
sleep 5
xset dpms force off
echo `date +%Y%m%d-%H:%M` "ylock resumed" >> /var/log/ydebug.log


