#!/bin/bash
# Base template.src version 1.4 last modified 2018.01.09 by y

y_start(){ :; }
y_exit(){ :; }
y_help(){ :; }

trap y_exit TERM HUP INT

# Uncomment this to allow colors on the console
#USE_COLOR="yes"

# This will enable positioning of a text to the end (-8 char) 
# of a line independent of window size
USE_POS="yes"

# Enable bell for warnings and errors
USE_BELL="yes"

# Source the function library
FSH="y_functions.sh"
FUNCTIONS=`which $FSH`
test $? != '0' && { echo Fatal Error!; exit 1; }
test -r ${FUNCTIONS} && source ${FUNCTIONS}

# define the following to match the program current state
PROGRAM_NAME="ymac_mkeys"
VERSION="0.0"
LAST_MOD="2018.01.10"

# Define log file here
LOG="/tmp/${0##*/}.log"

# Uncomment this if you need debug enabled
#Y_DEBUG="true"

# use these to set cleanup on exit
#MOUNTED=""		# y_exit will unmount them
#DELETE_ON_EXIT=""	# y_exit will delete them
#LAST_CMD=""		# y_exit will run it just before exit

SYS_KB_BL_BRIGTHNESS="/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight/brightness"

VOLUME_100="65536"

# command macros
MKEY_BRIGHTNESS_UP=""
MKEY_BRIGTHNESS_DOWN=""
MKEY_KBLIGHT_DOWN=""
MKEY_KBLIGHT_UP=""
MKEY_PLAY=""
MKEY_FWD=""
MKEY_BWD=""

pa_get_vol_cur (){
    x=`pactl list sinks | grep Volume | grep front | awk -F" " '{print $5}'`
    x=${x%\%*}
    echo $x
}

pa_set_vol_down (){
    if [ `pa_get_vol_cur` -ge 10 ]; then 
        pactl set-sink-volume 0 -10%
    else
        pactl set-sink-volume 0 0%
    fi
}

pa_set_vol_up (){
    if [ `pa_get_vol_cur` -le 90 ]; then 
        pactl set-sink-volume 0 +10%
    else
        pactl set-sink-volume 0 100%
    fi
}

pa_vol_mute_toggle (){
    pactl set-sink-mute 0 toggle
}


y_start
# ===================================================================================

# read command line parameters
while [ -n "$1" ] ; do
	case $1 in
		--help|-h)	y_help "[Options]"; y_exit;;		#; Help
        --pa-up)    pa_set_vol_up;;                     #; Increase audio volume
        --pa-down)  pa_set_vol_down;;                   #; Decrease audio volume
        --pa-mute)  pa_vol_mute_toggle;;                #; Toggle audio mute
	esac
	shift
done

pa_get_vol_cur
#pa_set_vol_up
#pa_vol_mute_toggle

# ===================================================================================
# Leave this as the last line
y_exit
