#!/bin/bash
# Base template.src version 1.4 last modified 2018.01.09 by y

y_start(){ :; }
y_exit(){ :; }
y_help(){ :; }

trap y_exit TERM HUP INT

# Uncomment this to allow colors on the console
#USE_COLOR="yes"

# This will enable positioning of a text to the end (-8 char) 
# of a line independent of window size
USE_POS="yes"

# Enable bell for warnings and errors
USE_BELL="yes"

# Source the function library
y_fsh (){
    FSH="y_functions.sh"
    FUNCTIONS=`which $FSH`
    test $? != '0' && { echo Fatal Error!; exit 1; }
    test -r ${FUNCTIONS} && source ${FUNCTIONS}
}
y_fsh

# define the following to match the program current state
PROGRAM_NAME="ymac_mkeys"
VERSION="0.1"
LAST_MOD="2018.01.11"

# Define log file here
LOG="/tmp/${0##*/}.log"

# Uncomment this if you need debug enabled
#Y_DEBUG="true"

# use these to set cleanup on exit
#MOUNTED=""		# y_exit will unmount them
#DELETE_ON_EXIT=""	# y_exit will delete them
#LAST_CMD=""		# y_exit will run it just before exit

SYS_KB_BL_BRIGTHNESS="/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight/brightness"
PA_SET_SINK_VOL="set-sink-volume 0"
PA_SINK_MUTE="set-sink-mute 0"
VOLUME_100="65536"

# help functions

# get current pulseaudio volume
pa_get_vol_cur (){
    x=`pactl list sinks | grep Volume | grep front | awk -F" " '{print $5}'`
    x=${x%\%*}
    echo $x
}

# reduce sound volume by 10%
pa_set_vol_down (){
    if [ `pa_get_vol_cur` -ge 10 ]; then 
        y_run pactl $PA_SET_SINK_VOL -10%
    else
        y_run pactl $PA_SET_SINK_VOL 0%
    fi
    y_debug 1 pa_vol_cur=`pa_get_vol_cur`%
}

# increase hound volume by 10%
pa_set_vol_up (){
    if [ `pa_get_vol_cur` -le 90 ]; then 
        y_run pactl $PA_SET_SINK_VOL +10%
    else
        y_run pactl $PA_SET_SINK_VOL 100%
    fi
    y_debug 1 pa_vol_cur=`pa_get_vol_cur`%
}

# toggle sound mute state
pa_vol_mute_toggle (){
    y_run pactl $PA_SINK_MUTE toggle
}


y_start
# ===================================================================================

# read command line parameters
while [ -n "$1" ] ; do
	case $1 in
		--help|-h)	y_help "[Options]"; y_exit;;		#; Help
        --debug|-D) Y_DEBUG="true";y_fsh;;              #; Enable debugging [Y_DEBUG]
        --pa-up)    pa_set_vol_up;;                     #; Increase audio volume
        --pa-down)  pa_set_vol_down;;                   #; Decrease audio volume
        --pa-mute)  pa_vol_mute_toggle;;                #; Toggle audio mute
	esac
	shift
done

# ===================================================================================
# Leave this as the last line
y_exit
