#!/bin/bash
# Based on template.src version 1.2 last modified 2006.09.29 by y
# Add your description here of the program here!

trap y_exit TERM HUP INT

y_start(){ :; }
y_exit(){ :; }
y_help(){ :; }

# Uncomment this to allow colors on the console
#USE_COLOR="yes"

# This will enable positioning of a text to the end (-8 char) 
# of a line independent of window size
USE_POS="yes"

# Enable bell for warnings and errors
USE_BELL="yes"

# Source the function library
FUNCTIONS="/bin/y_functions.sh"
test -r ${FUNCTIONS} && source ${FUNCTIONS}

# define the following to match the program current state
PROGRAM_NAME="yssh"
VERSION="0.5"
LAST_MOD="2017.12.14"

# Define log file here
LOG="/tmp/${0##*/}.log"

# Uncomment this if you need debug enabled
Y_DEBUG="true"

# use these to set cleanup on exit
#MOUNTED=""		# y_exit will unmount them
#DELETE_ON_EXIT=""	# y_exit will delete them
#LAST_CMD=""		# y_exit will run it just before exit

PORT="22250"
LOCAL_HOSTS="$HOME/.hosts"

y_start
# ===================================================================================

USER="$LOGNAME"
test -z "$1" && { y_help username@hostname; y_exit; }

HOST="$1"
x=`echo $1 | grep "@"`
y_debug 1 "$@"
if [ "$?" = "0" ] ; then
    USER=${1%@*}
    HOST=${1#*@}
fi
y_debug 1 "USER@HOST=$USER@$HOST"

x=`cat $LOCAL_HOSTS | grep "$HOST"`
y_debug 1 "x=$x"
IP=${x%' '*}
y_debug 1 "IP=[$IP]"

y_debug 2 "ssh $USER@$IP -p $PORT"

# ===================================================================================
# Leave this as the last line
y_exit

