#!/bin/bash
# Base template.src version 1.4 last modified 2018.01.09 by y

y_start(){ :; }
y_exit(){ :; }
y_help(){ :; }

trap y_exit TERM HUP INT

# Uncomment this to allow colors on the console
USE_COLOR="yes"

# This will enable positioning of a text to the end (-8 char) 
# of a line independent of window size
USE_POS="yes"

# Enable bell for warnings and errors
USE_BELL="yes"

# define the following to match the program current state
PROGRAM_NAME="ytest"
VERSION="0.0"
LAST_MOD="2018.01.11"

# Define log file here
LOG="/tmp/${0##*/}.log"

# Uncomment this if you need debug enabled
#Y_DEBUG="true"

# use these to set cleanup on exit
#MOUNTED=""		# y_exit will unmount them
#DELETE_ON_EXIT=""	# y_exit will delete them
#LAST_CMD=""		# y_exit will run it just before exit

Y_QUIET=""
Y_CONFIRM="true"

# Source the function library
ylib () {
    FSH="y_bash_lib"
    LIB=`which $FSH`
    test $? != '0' && { echo Fatal Error!; exit 1; }
    test -r ${LIB} && source ${LIB}
}
ylib


y_start
# ===================================================================================

# read command line parameters
while [ -n "$1" ] ; do
	case $1 in
		--help|-h)	y_help "[Options]"; y_exit;;    #; Help
        --test)     TEST=$TRUE;;                   #; [TEST]
        --quiet|-Q) Y_QUIET=$TRUE;;                #; Enable quiet mode [Y_QUIET]
        --debug|-D) Y_DEBUG=$TRUE;;                #; Enable debug mode [Y_DEBUG]
        --dry|-N)   Y_DRY_RUN=$TRUE;;              #; Execute dry run mode [Y_DRY_RUN]
        --nocolor)  USE_COLOR="";;                  #; Enable color output [USE_COLOR]
	esac
	shift
done

#Y_EXIT_ON_ERROR=$TRUE
Y_DEBUG_ON_ERROR=$TRUE
#y_init_screen
#y_run 'echo `date` - Hello > /tmp/ytest.x'
y_run grep xtest /etc/fstab
echo HAHO
y_run echo Hello World

# ===================================================================================
# Leave this as the last line
y_exit
