#!/bin/bash
# open xfce4-terminals helper utility

FONT=7
case $1 in
    --font) FONT=$2; shift; shift;;
esac
CMD="xfce4-terminal --font=$FONT --hide-borders --tab "

test -z "$*" && {
    echo missing parameters; exit;
}
while [ -n "$1" ] ; do 
	${CMD}$1; shift
done
