#!/bin/bash
# vim:set ts=2 sw=2:
# Base template2.src version 1.0 last modified 2018.01.11 by y

y_start(){ :; }
y_exit(){ :; }
y_help(){ :; }

trap y_exit TERM HUP INT

# Source the function library
ylib () {
  FSH="y_bash_lib"
  LIB=`which $FSH`
  test $? != '0' && { echo Fatal Error!; exit 1; }
  test -r ${LIB} && source ${LIB}
}
ylib

# Uncomment this to allow colors on the console
#USE_COLOR=$YES

# This will enable positioning of a text to the end (-8 char) 
# of a line independent of window size
#USE_POS=$YES

# Enable bell for warnings and errors
#USE_BELL=$YES

# define the following to match the program current state
PROGRAM_NAME="Update bin"
VERSION="0.1"
LAST_MOD="2021.02.04"

# Define log file here
LOG="/tmp/${0##*/}.log"

# Uncomment this if you need debug enabled
#Y_DEBUG=$TRUE

# use these to set cleanup on exit
#MOUNTED=""             # y_exit will unmount them
#DELETE_ON_EXIT=""      # y_exit will delete them
#LAST_CMD=""            # y_exit will run it just before exit

# Uncomment to make script quiet
#Y_QUIET=$FALSE

# Uncomment to ask for confirmation 
#Y_CONFIRM=$TRUE

# destination options: LOG,STDOUT,STDERR
#Y_MSG_DEST="STDOUT,LOG"

ylib

Y_TDIR="/usr/local/bin"
Y_SDIR="/xdir/proj/jenov/scripts"

echo 1
#Y_CMD="cp"
#y_init_screen
y_start
# ===================================================================================
HELP="Defaults"
echo 2
# read command line parameters
while [ -n "$1" ] ; do
  case $1 in
    --help|-h)	y_help "[Options]"; y_exit;;    #; Help [HELP]
    --log|-L)   export LOG="$2"; shift;;        #; Set LOG [LOG]
    --quiet|-Q) Y_QUIET="true";;                #; Enable quiet mode [Y_QUIET]
    --debug|-D) Y_DEBUG="true";;                #; Enable debug mode [Y_DEBUG]
    --dry|-N)   Y_DRY_RUN="true";;              #; Execute dry run mode [Y_DRY_RUN]
    --exit)     Y_EXIT_ON_ERROR=$TRUE;;         #; Exit on error [Y_EXIT_ON_ERROR]
    --edebug)   Y_DEBUG_ON_ERROR=$TRUE;;        #; Debug on error [Y_DEBUG_ON_ERROR]
    --nocolor)  USE_COLOR="";;                  #; Enable color output [USE_COLOR]
    --version|-V) y_version; y_exit;;           #; Display version and exit
    --tdir|-t)  Y_TDIR="$2";;                   #; Target dir [Y_TDIR]
    --sdir|-s)  Y_SDIR="$2";;                   #; Source dir [Y_SDIR]
    *)          y_fatal_error 2 "Unknown command";;
  esac
  shift
  echo 3
done

ylib

y_set_default Y_MSG_DEST "STDOUT,LOG"
y_set_default USE_COLOR $TRUE
y_set_default Y_DEBUG_ON_ERROR $FALSE
y_set_default Y_EXIT_ON_ERROR $FALSE

FLIST=`ls $Y_TDIR`
y_info 1[$FLIST]
for i in $FLIST ; do
  y_info $i
  y_run $Y_CMDx $Y_SDIR/$i $Y_TDIR
done


# ===================================================================================
# Leave this as the last line
y_exit
